ARG IMAGE_VERSION=latest

FROM registry.redhat.io/jboss-eap-7/eap-xp4-openjdk11-openshift-rhel8
ARG MAVEN_OPTS
ENV MAVEN_OPTS=$MAVEN_OPTS
ARG MAVEN_ARGS_APPEND
ENV MAVEN_ARGS_APPEND=$MAVEN_ARGS_APPEND
ARG MAVEN_S2I_ARTIFACT_DIRS=target
ENV MAVEN_S2I_ARTIFACT_DIRS=$MAVEN_S2I_ARTIFACT_DIRS

WORKDIR /build
RUN mkdir src
COPY --chown=jboss:root . ./src
ENV S2I_DESTINATION_DIR=/build
RUN /usr/local/s2i/assemble

